# Generated by Django 4.2.1 on 2023-05-25 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_id', models.CharField(max_length=255)),
                ('opening_date', models.DateTimeField(auto_now_add=True)),
                ('currency', models.CharField(choices=[('COP', 'Pesos Colombianos')], max_length=3)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Suspended', 'Suspended')], default='Open', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_number', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('expiration_date', models.DateField()),
                ('cvv', models.IntegerField()),
                ('card_type', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=200)),
                ('card_brand', models.CharField(choices=[('VISA', 'Visa'), ('MAST', 'MasterCard'), ('AMEX', 'American Express')], max_length=200)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=200)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.account')),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.card')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='credit_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_account', to='transactions.card'),
        ),
        migrations.AddField(
            model_name='account',
            name='debit_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debit_account', to='transactions.card'),
        ),
        migrations.AddField(
            model_name='account',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
