# Generated by Django 4.2.1 on 2023-05-25 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='credit_card',
        ),
        migrations.RemoveField(
            model_name='account',
            name='debit_card',
        ),
        migrations.AddField(
            model_name='account',
            name='cards',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.card'),
        ),
    ]
