# Generated by Django 4.2.1 on 2023-05-25 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_remove_account_credit_card_remove_account_debit_card_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='cards',
        ),
        migrations.AddField(
            model_name='card',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='transactions.account'),
        ),
    ]
