# Generated by Django 4.2.1 on 2023-05-25 08:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_remove_account_cards_card_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sede',
            field=models.CharField(choices=[('BARRANQUILLA', 'Barranquilla'), ('CARTAGENA', 'Cartagena'), ('SANTA MARTA', 'Santa Marta'), ('SINCELEJO', 'Sincelejo'), ('MONTERIA', 'Monteria')], default='Barranquilla', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
