# Generated by Django 4.2.1 on 2023-05-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_remove_transaction_card_transaction_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cuotas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
